In [ ]:
import pandas as pd
df=pd.read_csv('/content/makeSenseOfCensus.csv')
df.head()



age  education-num  race  ...  capital-loss  hours-per-week  income
0   39             13     4  ...             0              40       0
1   50             13     4  ...             0              13       0
2   38              9     4  ...             0              40       0
3   53              7     2  ...             0              40       0
4   28             13     2  ...             0              40       0

[5 rows x 8 columns]

In [ ]:
data_file ='/content/makeSenseOfCensus.csv'
import numpy as np
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)
data = np.genfromtxt(data_file, delimiter=",", skip_header=1,dtype=int)
data_float=np.genfromtxt(data_file, delimiter=",", skip_header=1)
data_str=np.genfromtxt(data_file,delimiter=',',skip_header=1,dtype=str)
# printing the data

print("\nData: \n\n", data)
#Printing the type of data
print("\nType of data: \n\n", type(data))



Data: 

 [[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [48 13  4 ...  0 58  1]
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]]

Type of data: 

 <class 'numpy.ndarray'>


In [ ]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
new_record

[[50, 9, 4, 1, 0, 0, 40, 0]]

In [ ]:
#Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.
age_col=data[:,0]
age_col

array([39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 37, 30, 23, 32, 40, 34, 25,
       32, 38, 43, 40, 54, 35, 43, 59, 56, 19, 54, 39, 49, 23, 20, 45, 30,
       22, 48, 21, 19, 31, 48, 31, 53, 24, 49, 25, 57, 53, 44, 41, 29, 25,
       18, 47, 50, 47, 43, 46, 35, 41, 30, 30, 32, 48, 42, 29, 36, 28, 53,
       49, 25, 19, 31, 29, 23, 79, 27, 40, 67, 18, 31, 18, 52, 46, 59, 44,
       53, 49, 33, 30, 43, 57, 37, 28, 30, 34, 29, 48, 37, 48, 32, 76, 44,
       47, 20, 29, 32, 17, 30, 31, 42, 24, 38, 56, 28, 36, 53, 56, 49, 55,
       22, 21, 40, 30, 29, 19, 47, 20, 31, 35, 39, 28, 24, 38, 37, 46, 38,
       43, 27, 20, 49, 61, 27, 19, 45, 70, 31, 22, 36, 64, 43, 47, 34, 33,
       21, 52, 48, 23, 71, 29, 42, 68, 25, 44, 28, 45, 36, 39, 46, 18, 66,
       27, 28, 51, 27, 28, 27, 21, 34, 18, 33, 44, 43, 30, 40, 37, 34, 41,
       53, 31, 58, 38, 24, 41, 47, 41, 23, 36, 40, 35, 24, 26, 19, 51, 42,
       37, 18, 36, 35, 58, 17, 44, 37, 35, 60, 54, 37, 50, 38, 45, 25, 31,
       64, 90, 54, 53, 18

In [ ]:
#Find the max age and store it in a variable called 'max_age
max_age=np.max(data[:,0])
max_age

90

In [ ]:
#Find the min age and store it in a variable called 'min_age'.
min_age=np.min(data[:,0])
min_age

17

In [ ]:
#Find the mean of the age and store it in a variable called 'age_mean'.
age_mean=np.mean(data[:,0])
age_mean

38.051

In [ ]:
#Find the standard deviation of the age and store it in a variable called 'age_std'
age_std=np.std(data[:,0])
age_std

13.342803266180612

In [ ]:
#Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)
race_0 = data[data[:,2]==0]
race_0

array([[34,  4,  0,  1,  0,  0, 45,  0],
       [35, 10,  0,  0,  0,  0, 40,  0],
       [60,  6,  0,  0,  0,  0, 10,  0],
       [51,  9,  0,  1,  0,  0, 40,  0],
       [25, 10,  0,  0,  0,  0, 20,  0],
       [20,  9,  0,  1,  0,  0, 48,  0],
       [23, 10,  0,  0,  0,  0, 25,  0],
       [29,  9,  0,  1,  0,  0, 40,  0],
       [27, 12,  0,  1,  0,  0, 40,  0],
       [31, 12,  0,  0,  0,  0, 40,  0]])

In [ ]:
race_1 = data[data[:,2]==1]
race_1

array([[  30,   13,    1,    1,    0,    0,   40,    1],
       [  40,   11,    1,    1,    0,    0,   40,    1],
       [  54,   10,    1,    1,    0,    0,   60,    1],
       [  30,    9,    1,    0,    0, 1573,   35,    0],
       [  49,   10,    1,    1,    0,    0,   40,    1],
       [  33,   13,    1,    0,    0,    0,   40,    0],
       [  44,   14,    1,    0,    0,    0,   40,    0],
       [  28,    9,    1,    0,    0,    0,   40,    0],
       [  60,    9,    1,    1,    0,    0,   40,    0],
       [  42,    9,    1,    1,    0,    0,   40,    1],
       [  37,   10,    1,    1,    0,    0,   75,    1],
       [  39,   14,    1,    0, 3464,    0,   40,    0],
       [  21,   10,    1,    0,    0,    0,   25,    0],
       [  24,   10,    1,    0,    0,    0,   40,    0],
       [  34,   14,    1,    1, 7298,    0,   35,    1],
       [  27,   10,    1,    1,    0, 1980,   40,    0],
       [  40,   11,    1,    1,    0,    0,   40,    1],
       [  55,    9,    1,    0,

In [ ]:
race_2 = data[data[:,2]==2]
race_2

array([[  53,    7,    2,    1,    0,    0,   40,    0],
       [  28,   13,    2,    0,    0,    0,   40,    0],
       [  49,    5,    2,    0,    0,    0,   16,    0],
       [  37,   10,    2,    1,    0,    0,   80,    1],
       [  32,   12,    2,    1,    0,    0,   50,    0],
       [  54,    9,    2,    0,    0,    0,   20,    0],
       [  35,    5,    2,    1,    0,    0,   40,    0],
       [  20,   10,    2,    1,    0,    0,   44,    0],
       [  22,   10,    2,    1,    0,    0,   15,    0],
       [  57,   13,    2,    1,    0,    0,   40,    1],
       [  31,   13,    2,    0,    0,    0,   40,    0],
       [  28,   10,    2,    0,    0,    0,   25,    0],
       [  32,    9,    2,    1,    0,    0,   40,    0],
       [  49,   11,    2,    1,    0,    0,   40,    1],
       [  30,   13,    2,    1,    0,    0,   40,    0],
       [  19,   10,    2,    1,    0,    0,   35,    0],
       [  46,   12,    2,    0,    0,    0,   36,    0],
       [  31,    9,    2,    0,

In [ ]:
race_3 = data[data[:,2]==3]
race_3

array([[  25,   10,    3,    0,    0,    0,   40,    0],
       [  33,   10,    3,    0,    0,    0,   40,    0],
       [  65,    7,    3,    1,    0,    0,   40,    0],
       [  28,    4,    3,    1,    0, 2179,   40,    0],
       [  44,    7,    3,    0,    0,    0,   46,    0],
       [  40,   13,    3,    0,    0,    0,   55,    1]])

In [ ]:
race_4 = data[data[:,2]==4]
race_4

array([[39, 13,  4, ...,  0, 40,  0],
       [50, 13,  4, ...,  0, 13,  0],
       [38,  9,  4, ...,  0, 40,  0],
       ...,
       [48, 13,  4, ...,  0, 58,  1],
       [40, 10,  4, ...,  0, 40,  0],
       [39, 13,  4, ...,  0, 50,  1]])

In [ ]:
#Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively
len_0=len(race_0)
print(len_0)
len_1=len(race_1)
print(len_1)
len_2=len(race_2)
print(len_2)
len_3=len(race_3)
print(len_3)
len_4=len(race_4)
print(len(race_4))

10
27
110
6
847


In [36]:
#Find out which is the race with the minimum no. of citizens
min_race= min(len_0, len_1, len_2, len_3, len_4)
if min_race==len_0:
  print("race_0 has the min citizen",len_0)
elif min_race==len_1:
  print('race_1 has the min citizen',len_1)
elif min_race==len_2:
  print('race_2 has the min citizen',len_2)
elif min_race==len_3:
  print('race_3 has the min citizen',len_3)
elif min_race==len_4:
  print('race_4 has the min citizen',len_4)
else:
  pass

race_3 has the min citizen 6


In [37]:
#Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )
minority_race= min(len_0,len_1,len_2,len_3,len_4)
minority_race

6

In [31]:
#Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)
senior_citizens= data[data[:,0] > 60]
senior_citizens

array([[   79,    10,     4,     1,     0,     0,    20,     0],
       [   67,     6,     4,     1,     0,     0,     2,     0],
       [   76,    14,     4,     1,     0,     0,    40,     1],
       [   61,     9,     4,     1,     0,     0,    40,     0],
       [   70,    10,     4,     1,     0,     0,    40,     0],
       [   64,     7,     4,     1,     0,  2179,    40,     0],
       [   71,    10,     2,     1,     0,  1816,     2,     0],
       [   68,     2,     4,     0,     0,     0,    20,     0],
       [   66,    11,     4,     0,     0,     0,    20,     0],
       [   64,     2,     4,     1,     0,     0,    40,     0],
       [   90,     9,     2,     1,     0,  2206,    40,     0],
       [   66,     9,     4,     1,  1409,     0,    50,     0],
       [   75,    11,     4,     0,     0,     0,    20,     0],
       [   65,     9,     4,     0,     0,     0,    40,     0],
       [   64,     9,     4,     1,     0,     0,    40,     1],
       [   61,     9,    

In [47]:
#Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'
working_hours_sum=sum(senior_citizens[:,6])
working_hours_sum


1917

In [48]:
#Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len
senior_citizens_len=len(senior_citizens)
senior_citizens_len

61

In [49]:
#Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.
avg_working_hours = working_hours_sum/senior_citizens_len
avg_working_hours

31.42622950819672

In [50]:
#Print 'avg_working_hours' and see if the govt. policy is followed.
if avg_working_hours <= 25:
  print("gov police is followed")
else:
  print("gov police is not followed")


gov police is not followed


In [83]:
#Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.
high_edu=data[data[:,1]>10]
print(len(high_edu))
print(sum(high_edu))


327
[ 12745   4236   1221    222 361938  42747  14097    140]


In [84]:
low_edu=data[data[:,1]<=10]
print(len(low_edu))
print(sum(low_edu))


673
[ 25306   5848   2432    449 226588  50213  25779     92]


In [88]:
#Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.
avg_pay_high=high_edu[:,7]
print(round(avg_pay_high.mean(),2))
avg_pay_low=low_edu[:,7]
print(round(avg_pay_low.mean(),2))

0.43
0.14
